config/routes.rb
Tasks::Application.routes.draw do

  resources :attachments
  
  get 'projects/dashboard'
  resources :projects do
    resources :tasks do
      get 'complete'
      collection do
        get 'people'
      end
    end
    resources :collaborators
  end

  devise_for :users

  get "home/after_sign_in"
  get "home/index"

  root :to => 'home#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  require 'pp'
  
  belongs_to :author, :class_name => "User", :foreign_key => "author_id"
  belongs_to :handler, :class_name => "User", :foreign_key => "assignee_id"        
  belongs_to :project    
  has_many :attachments, :dependent => :destroy      
  
  enum_attr :due, [['OverDue', 0, 'OverDue'], ['ASAP', 10, 'ASAP'], ['Today', 20, 'Today'], 
   ['Tomorrow', 30, 'Tomorrow'], ['ThisWeek', 40, 'ThisWeek'], ['NextWeek', 50, 'NextWeek'], 
   ['ThisMonth', 60, 'ThisMonth'], ['NextMonth', 70, 'NextMonth'], ['ThisYear', 80, 'ThisYear'], ['Nil', 999999, 'Nil']]
  # tom. tmr. 2moro.
  
  def self.parse(input)
    task = Task.new
    
    parsed = input.split(' due ')
    if parsed.size == 2
      task.title = parsed[0]
      
      case parsed[1].strip.downcase
      when 'asap'
        task.due = DUE_ASAP
      when 'today'
        task.due = DUE_TODAY
      when 'tomorrow', 'tmr.', 'tom.', '2moro.'
        task.due = DUE_TOMORROW
      when 'this week', 'thisweek'
        task.due = DUE_THISWEEK
      when 'next week', 'nextweek'
        task.due = DUE_NEXTWEEK
      when 'this month', 'thismonth'
        task.due = DUE_THISMONTH
      when 'next month', 'nextmonth'
        task.due = DUE_NEXTMONTH
      when 'this year', 'thisyear'
        task.due = DUE_THISYEAR
      else
        task.due = DUE_NIL
      end
    elsif parsed.size == 1
      task.title = parsed[0]
      task.due = DUE_NIL
    else
      # TODO
    end
    
    task
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  require 'pp'
  layout '2column'
  before_filter :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks.where('status = 0').order('created_at DESC')
    
    # @tasks_row = @project.tasks.where('status = 0').order('due')
    # @tasks_row.each do |task|
    #   today = Date.today
    #   task_date = task.created_at.to_date
    # 
    #   case task.due
    #   when Task::DUE_ASAP
    #   when Task::DUE_TODAY
    #     if task_date < today
    #       task.due = Task::DUE_OVERDUE
    #     end
    #   when Task::DUE_TOMORROW
    #     if task_date + 1 == today
    #       task.due = Task::DUE_TODAY
    #     elsif task_date + 1 < today
    #       task.due = Task::DUE_OVERDUE
    #     end
    #   when Task::DUE_THISWEEK
    #     if today - task_date == 7 - task_date.wday - 2
    #       task.due = Task::DUE_TOMORROW
    #     elsif today - task_date == 7 - task_date.wday - 1
    #       task.due = Task::DUE_TODAY
    #     elsif today - task_date >= 7 - task_date.wday
    #       task.due = Task::DUE_OVERDUE
    #     end
    #   when Task::DUE_NEXTWEEK
    #     # TODO
    #   when Task::DUE_THISMONTH
    #     days_in_month = Time.days_in_month(Time.now.month)
    #     if today.month != task_date.month
    #       task.due = Task::DUE_OVERDUE
    #     elsif days_in_month - today.mday == 1
    #       task.due = Task::DUE_TOMORROW
    #     elsif days_in_month - today.mday == 0
    #       task.due = Task::DUE_TODAY
    #     # TODO. due_thisweek, due_nextweek
    #     end
    #   when Task::DUE_NEXTMONTH
    #     if (task_date >> 1).month != today.month
    #       task.due = Task::DUE_OVERDUE
    #     # elsif 
    #     #   task.due = Task::DUE_TOMORROW
    #     # elsif
    #     #   task.due = Task::DUE_TODAY
    #     # TODO. due_thisweek, due_nextweek
    #     elsif today.month == task_date.month
    #       task.due = Task::DUE_THISMONTH
    #     end 
    #   when Task::DUE_THISYEAR
    #     # TODO
    #   else
    #   end
    # end
    # 
    # @tasks = @tasks_row.sort_by &:due
    @new_task = Task.new
#    @tasks.sort! { |t| t.due }
#    @tasks = current_user.todos.where('status = 0').order('created_at DESC')
#    @completed = current_user.todos.where('status = 1').order('updated_at DESC')
  #  @tasks = Task.where('status = 0').order("content")
  #  @completed = Task.where('status = 1').order("updated_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end        
  
  def complete 
    pp params[:task_id]
    pp @task = Task.find(params[:task_id])
    @task.status = 1
    @task.save
    
    respond_to do |format|
      format.js
    end
  end

  def uncomplete 
    @task = Task.find(params[:id])
    @task.status = 0
    @task.save
    
    respond_to do |format|
      format.js
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
    @new_task = Task.new

    respond_to do |format|
      format.html { render :layout => "1column" } # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
    @task.status = 0

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @project = Project.find(params[:project_id])
    @task = Task.new
    @task.title = params[:task][:title]
#    @task = Task.parse(params[:task][:title])
    @task.project_id = @project.id
    @task.detail = params[:task][:detail]
    @task.author_id = current_user.id
    @task.assignee_id = params[:task][:assignee_id]
    pp params[:has_attachment]
    respond_to do |format|
      if @task.save
        format.js
        format.html { redirect_to project_tasks_url(@project), notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])

    if request.format == 'application/json' # handle files upload
      @attach = Attachment.create(:task_id => @task.id, :file => params[:files][0])

      respond_to do |format|
        format.json {
          pp @attach.to_jq_upload.to_json
          render :json => @attach.to_jq_upload.to_json
        }
      end
    else # basic attributes update
        respond_to do |format|
        if @task.update_attributes(params[:task])
          format.html { redirect_to project_tasks_url(@project), notice: 'Task was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to project_tasks_url(@project), notice: 'Task was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  
  # kind of list
  def people
    @project = Project.find(params[:project_id])
    @collaborators = @project.collaborators
    
    render :layout => "1column"
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/___commented.html.erb
<p class="navbar-text pull-right">
<% if signed_in? %>
Hello <%= current_user.email %>! <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
<% else %>
<%= link_to 'Sign In', new_user_session_path %>
<% end %>
</p>



<!--
<h1>Tasks</h1>
<p id="notice"><%= notice %></p>
<%= button_to '+ New Task', new_project_task_path(@project), :method => :get %>
<div class="todo">
	<div class="task_anchor"></div>
	<% @tasks.each do |task| %>
	  <div class='task'>
		<span class='checkbox'><%= check_box_tag :complete, task.id %></span><span class='content'><%= task.content %></span>
		<%= image_tag 'delete.png', :class => 'delete' %><%= link_to image_tag('edit.png'), edit_project_task_path(@project, task), :class => 'edit' %>
	  </div>
	<% end %>
</div>          

<div class="legend" id="test">Completed: <span class='completed-count'><%= @completed.size %></span></div>
<div class="completed">
	<div class="completed_anchor"></div>                                                     
	<% @completed.each do |c| %>
		<div class='task'>
			<span class='checkbox'><%= check_box_tag :uncomplete, c.id, :checked => 'checked' %></span><span><%= c.content %></span>
			<%= image_tag 'delete.png', :class => 'delete' %>
		</div>
	<% end %>
</div>
-->
<script>

$(function() {  

	$('.delete').click(function(){
		var id = $(this).prev().prev().children().attr('value');
		$.ajax({          
			type: 'DELETE',
			url: "/tasks/" + id,
			success: remove_task(this)
		});
	});                              
	function remove_task(e){  
		$(e).parent().fadeOut('slow', function(){
			$(e).parent().remove();
		});
	}
	
	
	$(':checkbox').click(function(){
	  	var id = $(this).attr("value");
		if ($(this).attr("id") == 'complete'){
			$.ajax({
				url: "/tasks/" + id + "/complete",
				success: complete_check(this)
			});                               
		}
		else{
			$.ajax({
				url: "/tasks/" + id + "/uncomplete",
				success: uncomplete_check(this)
			});                               
		}
	}); 

	/*    
	function complete_check(e){
		$(e).parent().parent().fadeOut('fast', function(){
			var rebirth = $(this).clone(true, true);
			rebirth.find(':checkbox').attr("id", "uncomplete");
			rebirth.find(':checkbox').attr("name", "uncomplete");
			$('.completed_anchor').after(rebirth);
			rebirth.fadeIn('fast');
			$(this).remove();
		});
	}

	function uncomplete_check(e){
		$(e).parent().parent().fadeOut('fast', function(){
			var rebirth = $(this).clone(true, true);
			rebirth.find(':checkbox').attr("id", "complete");
			rebirth.find(':checkbox').attr("name", "complete");
			$('.task_anchor').after(rebirth);
			rebirth.fadeIn('slow');
			$(this).remove();
		});
	}
	*/

	function complete_check(e){
	    var rebirth = $(e).parent().parent().clone(true, true);
		rebirth.find(':checkbox').attr("id", "uncomplete");
		rebirth.find(':checkbox').attr("name", "uncomplete");
	    $(e).parent().parent().remove();
	    $('.completed_anchor').after(rebirth);

		var c_count = $('.completed-count').text();
		$('.completed-count').text(parseInt(c_count) + 1);
	}

	function uncomplete_check(e){
	    var rebirth = $(e).parent().parent().clone(true, true);
		rebirth.find(':checkbox').attr("id", "complete");
		rebirth.find(':checkbox').attr("name", "complete");
	    $(e).parent().parent().remove();
	    $('.task_anchor').after(rebirth);

		var c_count = $('.completed-count').text();
		$('.completed-count').text(parseInt(c_count) - 1);
	}
	
});

</script>

app/views/tasks/_attach.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3>Upload attachments</h3>
</div>

<%= form_for([@project, @task], :html => {:id => "task_attachment", :class => "form-horizontal upload_support", :style=>"margin-bottom:0px;"}) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="modal-body task-form clearfix">
		<div class="control-group" id="attachments-zone"><i class="icon-file"></i>
			<em>Just drag and drop files here...or...</em>
			<p><input class="input-file" type="file" multiple></p>
			<% attachments = @task.attachments %>
			<% attachments.each do |file| %>
				<p><%= link_to file.file_name, file.url_path, :target => "_blank" %>
					<i class="icon-remove" id="<%= file.id %>"></i></p>
			<% end %>
		</div>
	</div>
	<div class="modal-footer">
	  <a href="#" class="btn btn-primary" data-dismiss="modal">Done</a>
	</div>
<% end %>

<%= javascript_include_tag "my_upload" %>
<script>
$(function(){
	$(".btn-primary").click(function(){
		window.location.href = "/projects/" + <%= @project.id %> + "/tasks/" ;
	});
}); 
</script>

app/views/tasks/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h3>Create task</h3>
</div>

<%= form_for([@project, @new_task], :html => {:class => "form-horizontal new_task_form", :style=>"margin-bottom:0px;"}, :remote => true) do |f| %>
  <% if @new_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @new_task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="modal-body task-form clearfix">
			<div class="control-group"><i class="icon-pencil"></i>
			<%= f.text_field :title, :class => 'input-xxxlarge new_task_title', :placeholder => "The whole story or a short summary..." %></div>
			<div class="control-group"><i class="icon-tasks"></i>
			<%= f.text_area :detail, :class => 'input-xxxlarge', :rows => 8, :placeholder => "Details if necessary..." %></div>
<!--			<div class="control-group" id="due"><i class="icon-time"></i>
				<span class="select-block due">ASAP</span><span class="select-block due">Today</span><span class="select-block due">Tomorrow</span><span class="select-block due">ThisWeek</span>
			</div>-->
			<div class="control-group" id="assignee"><i class="icon-user"></i>
				<% @project.collaborators.each do |c| %><span class="select-block assignee"><%= c.user.username %></span><span class="hidden"><%= c.user_id%></span><% end %>
			</div>
	</div>
	<%= f.hidden_field :assignee_id %>
	<%= hidden_field_tag :has_attachment, 0 %>
	<div class="modal-footer">
	  <a href="#" class="btn" data-dismiss="modal">Cancel</a>
	  <%= f.submit 'Done', :class => 'btn btn-primary' %>
	  <a href="#" class="btn btn-primary continue">Continue, attach files >></a>
	</div>
<% end %>
<script> 
$(function(){
	$(".select-block").click(function(){
		$(this).siblings().removeClass('active');
		$(this).addClass('active');
		var select_id = $(this).parent().attr('id');
		if( select_id == 'due'){
			// TODO..
		}
		else if(select_id == 'assignee'){
			$('#task_assignee_id').val($(this).next().text());
		}
		else{
			alert("what's " + select_id);
		}
	});
	
	$(".continue").click(function(){
		$("#has_attachment").val(1);
		$(".new_task_form").submit();
	});		
}); 
</script>

app/views/tasks/complete.js.erb
'success'

app/views/tasks/create.js.erb
<% if params[:has_attachment] == '1' %>
	$("#task-form").html('<%= escape_javascript(render "attach") %>');
<% else %>
	<% flash[:notice] = 'Task was successfully created.' %>
	window.location.href = "/projects/" + <%= @project.id %> + "/tasks/";
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@project) %>

app/views/tasks/index.html.erb
<div class="content-header">
	<div class="header-inner">
		<% if notice %><span class="notice"><%= notice %></span><% end %><h2>Tasks</h2><%= hidden_field_tag :project_id, @project.id %>
	</div>
</div>
<div class="tasks">
	<% @tasks.each do |task| %>
	<div class="task" id="<%= task.id %>">
		<div class="task-content">
			<%= check_box_tag :complete, task.id %> <% if task.due != Task::DUE_NIL %><span class="due"><%= task.due_name %></span> <% end %>
			<span class="title"><%= task.title %></span>
			<div class="user"><%= task.handler.username %></div>
		</div>
	</div>
	<% end %>
</div>
<div class="content-footer">
	<div class="footer-inner">
		<h4>- end -</h4>
	</div>
</div>

<div id="task-detail-wrapper" style="display:none;">
	<div class="task-detail">
		<div class="clearfix">
			<div class="literal">
				<%= text_field_tag :title, nil, :class => "input-xlarge" %>
				<%= text_area_tag :detail, nil, :class => "input-xlarge", :rows => 3 %>
			</div>
			<div class="attachments">
			</div>
		</div>
		<div>
			<%= submit_tag "Save Changes", :class => "btn btn-primary mr5" %><a href="" class="btn">Cancel</a>
		</div>
	</div>
</div>

<script>
$(function() {  

	$('.title').click(function(){          
		var project_id = $('#project_id').val();
		var task_id = $(this).parent().parent().attr("id");
		window.location.href = "/projects/" + project_id + "/tasks/" + task_id;
	});

// 	$('.task').click(function(){
// 		$(this).after($("#task-detail-wrapper"));
// 		$("#task-detail-wrapper").slideDown("slow");
// //		$(this).after();
// 	});
	
	$(':checkbox').click(function(){
  	var task_id = $(this).attr("value");
		var project_id = $('#project_id').val();
		$.ajax({
			url: "/projects/" + project_id + "/tasks/" + task_id + "/complete",
			success: complete_check(this)
		});                               
	});

	function complete_check(e){
		$(e).parent().parent().fadeOut('slow');
	}
	
});
</script>

app/views/tasks/new.html.erb
<h1><%= @project.name %></h1>
<h3>New task</h3><br />

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@project) %>

app/views/tasks/people.html.erb
<div id="masonry-container">
	<% @collaborators.each do |c| %>
	<div class="item">
		<div class="content-header">
			<div class="header-inner mini-profile">
				<div class="account-summary">
					<div class="">
						<%= image_tag 'default_profile.png', :class => "avatar size32" %>
						<b class="fullname"><%= c.user.username %></b>
						<small class="role">Java developer</small>
					</div>
				</div>
			</div>
			<% tasks = @project.tasks.where("assignee_id = ? AND status = 0", c.user_id) %>
			<% tasks.each do |t| %>
			<div class="task"><%= t.title %></div>
			<% end %>
		</div>
	</div>
	<% end %>
</div>

app/views/tasks/show.html.erb
<div class="content-header">
	<div class="header-inner">
		<%= link_to 'Delete', [@project, @task], :method => 'delete', :confirm => "Are you sure?", :class => 'fr' %><h2>Task detail</h2>
	</div>
	<div class="content">
		<%= form_for([@project, @task], :html => {:id => "task-edit-form", :class => "form-horizontal upload_support", :style=>"margin-bottom:0px;"}) do |f| %>
		  <% if @task.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

		      <ul>
		      <% @task.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>

			<div class="task-edit-form clearfix">
				<div class="fl literal mr20">
					<div class="control-group"><i class="icon-pencil"></i>
					<%= f.text_field :title, :class => 'input-xxlarge', :placeholder => "The whole story or a short summary..." %></div>
					<div class="control-group"><i class="icon-tasks"></i>
					<%= f.text_area :detail, :class => 'input-xxlarge', :rows => 15, :placeholder => "Details if necessary..." %></div>
<!--					<div class="control-group" id="due"><i class="icon-time"></i>
						<span class="select-block due">ASAP</span><span class="select-block due">Today</span><span class="select-block due">Tomorrow</span><span class="select-block due">ThisWeek</span>
					</div>-->
					<div class="control-group" id="assignee"><i class="icon-user"></i>
						<% @project.collaborators.each do |c| %><span class="select-block assignee<%if @task.assignee_id == c.user.id%> active<%end%>"><%= c.user.username %></span><span class="hidden"><%= c.user_id%></span><% end %>
					</div>
					<hr />
					<%= f.submit 'Done', :class => 'btn btn-primary mr5' %><%= link_to "Cancel", project_tasks_path(@project), :class => 'btn' %>
				</div>
				<div class="fl attachments mr20">
					<div class="control-group" id="attachments-zone"><i class="icon-file"></i>
						<em>Just drag and drop files here...or...</em>
						<p><input class="input-file" type="file" multiple></p>
						<% attachments = @task.attachments %>
						<% attachments.each do |file| %>
							<p><%= link_to file.file_name, file.url_path, :target => "_blank" %>
								<i class="icon-remove" id="<%= file.id %>"></i></p>
						<% end %>
					</div>
				</div>
				<div class="fl comments">
					<div class="control-group">
						<i class="icon-edit"></i>
						Not any comment
					</div>
				</div>
			</div>
			<%= f.hidden_field :assignee_id %>
		<% end %>
	</div>
</div>

<%= javascript_include_tag "my_upload" %>
<script>
$(function() {
	$(".select-block").click(function(){
		$(this).siblings().removeClass('active');
		$(this).addClass('active');
		var select_id = $(this).parent().attr('id');
		if( select_id == 'due'){
			// TODO..
		}
		else if(select_id == 'assignee'){
			$('#task_assignee_id').val($(this).next().text());
		}
		else{
			alert("what's " + select_id);
		}
	});
});
</script>

app/views/tasks/uncomplete.js.erb
"success"