config/routes.rb
Tasks::Application.routes.draw do

  resources :attachments
  
  get 'projects/dashboard'
  resources :projects do
    resources :tasks do
      get 'complete'
      collection do
        get 'people'
      end
    end
    resources :collaborators
  end

  devise_for :users

  get "home/after_sign_in"
  get "home/index"

  root :to => 'home#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base    
  belongs_to :project
  belongs_to :user
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  require 'pp'
  
  # GET /collaborators
  # GET /collaborators.json
  def index
    @project = Project.find(params[:project_id])
    @collaborators = @project.collaborators
    @collaborator = Collaborator.new
    respond_to do |format|
      format.html { render :layout => "admin" }# index.html.erb
      format.json { render json: @collaborators }
    end
  end

  # POST /collaborators
  # POST /collaborators.json
  def create
    @project = Project.find(params[:project_id])
    pp @user = User.find_by_email(params[:email])
    if @user.nil?
      redirect_to project_collaborators_url(@project), notice: "user '#{params[:email]}' does not exist."
      return
    end
    
    if @project.collaborators.find_by_user_id(@user.id)
      redirect_to project_collaborators_url(@project), notice: "user '#{params[:email]}' already exist."
      return
    end
    if @user.id == @project.owner.id
      redirect_to project_collaborators_url(@project), notice: "user '#{params[:email]}' already exist."
      return
    end
    
    @collaborator = @project.collaborators.build(:user_id => @user.id)

    respond_to do |format|
      if @collaborator.save
        format.html { redirect_to project_collaborators_url(@project), notice: 'Collaborator was successfully added.' }
        format.json { render json: @collaborator, status: :created, location: @collaborator }
      else
        format.html { render action: "new" }
        format.json { render json: @collaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collaborators/1
  # DELETE /collaborators/1.json
  def destroy
    @project = Project.find(params[:project_id])
    @collaborator = Collaborator.find(params[:id])
    @collaborator.destroy

    respond_to do |format|
      format.html { redirect_to project_collaborators_url(@project) }
      format.json { head :no_content }
    end
  end



# not needed methods
private
  # GET /collaborators/1
  # GET /collaborators/1.json
  def show
    @collaborator = Collaborator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collaborator }
    end
  end

  # GET /collaborators/new
  # GET /collaborators/new.json
  def new
    @project = Project.find(params[:project_id])
    @collaborator = Collaborator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collaborator }
    end
  end

  # GET /collaborators/1/edit
  def edit
    @collaborator = Collaborator.find(params[:id])
  end

  # PUT /collaborators/1
  # PUT /collaborators/1.json
  def update
    @collaborator = Collaborator.find(params[:id])

    respond_to do |format|
      if @collaborator.update_attributes(params[:collaborator])
        format.html { redirect_to @collaborator, notice: 'Collaborator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @collaborator.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/views/collaborators/_form.html.erb
<%= form_for([@project, @collaborator], :html => {:class => "form-inline"}) do |f| %>
  <% if @collaborator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collaborator.errors.count, "error") %> prohibited this collaborator from being saved:</h2>

      <ul>
      <% @collaborator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Email" %>
    <%= text_field_tag :email, nil, :class => "controls" %>
    <%= f.submit 'Add', :class => "btn btn-primary" %>

  </div>
  <div class="actions">
  </div>
<% end %>

app/views/collaborators/edit.html.erb
<h1>Editing collaborator</h1>

<%= render 'form' %>

<%= link_to 'Show', @collaborator %> |
<%= link_to 'Back', collaborators_path %>

app/views/collaborators/index.html.erb
<% @function = "Collaborators" %>
<p id="notice"><%= notice %></p>
<%= render 'form' %>
<hr>
<table>
<% @collaborators.each do |collaborator| %>
  <tr>
    <td width="300"><%= collaborator.user.email %></td>
    <td><%= link_to 'Remove', [@project, collaborator], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/collaborators/new.html.erb
<h1><%= @project.name %></h1>
<h2>> New collaborator</h2>

<%= render 'form' %>

<%= link_to 'Back', project_collaborators_path(@project) %>

app/views/collaborators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @collaborator.project_id %>
</p>

<p>
  <b>User:</b>
  <%= @collaborator.user_id %>
</p>


<%= link_to 'Edit', edit_collaborator_path(@collaborator) %> |
<%= link_to 'Back', collaborators_path %>