config/routes.rb
Tasks::Application.routes.draw do

  resources :attachments
  
  get 'projects/dashboard'
  resources :projects do
    resources :tasks do
      get 'complete'
      collection do
        get 'people'
      end
    end
    resources :collaborators
  end

  devise_for :users

  get "home/after_sign_in"
  get "home/index"

  root :to => 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :owner, :class_name => "User", :foreign_key => "owner_id" 
  has_many :tasks
  has_many :collaborators
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout '1column'
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    session[:project_id] = @project.id

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html { render :layout => "white" } # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    render :layout => 'admin'
  end

  # POST /projects
  # POST /projects.json
  def create   
    Project.transaction do
      @project = current_user.projects.build(params[:project])
      @project.save
      Collaborator.create(:project_id => @project.id, :user_id => current_user.id)
    end

    respond_to do |format|
      if @project
        format.html { redirect_to project_tasks_url(@project), notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to edit_project_url(@project), notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  

  def dashboard
    
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project, :html => {:class=>'form-inline'}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <label>Project Name</label> <%= f.text_field :name, :size => 50, :class => "controls" %> <%= f.submit :class => 'btn btn-primary' %>
<% end %>

app/views/projects/dashboard.html.erb
<h2>Dashboard</h2>

app/views/projects/edit.html.erb
<% @function = "Edit" %>
<p id="notice"><%= notice %></p>
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="pull-right h1-buttons">
<%= button_to '+ New Project', new_project_path, :method => :get, :class => "btn btn-primary" %>
</div>
<h1>Projects</h1>
<br />

<table class="" style="width:400px;">
	<tbody>
	<% @projects.each do |project| %>
	  <tr>
	    <td>→ <%= link_to project.name, project %></td>
		<td width="120">
			<div class="btn-group">
			  <button class="btn btn-small"><%= link_to 'Edit', edit_project_path(project) %></button>
			  <button class="btn btn-small"><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></button>
			</div>
		</td>
	  </tr>
	<% end %>
	</tbody>
</table>

app/views/projects/new.html.erb
<div class="page-top page-top-1">
	<h2>New project</h2>
</div>
<div class="well">
	<blockquote style="width:600px;">
		<p>Project is the game of trade-off among people, budget and time-frame.</p>
		<small>54</small>
	</blockquote>
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class="pull-right h1-buttons">
	<div class="btn-group">
	  <button class="btn btn-success" id="collaborators">Invite Collaborators</button>
	  <button class="btn btn-primary" id="new">+ New Tasks</button>
	</div>
</div>
<h1><%= @project.name %></h1>
<div id="file-uploader-demo1">		
	<noscript>			
		<p>Please enable JavaScript to use file uploader.</p>
		<!-- or put a simple form for upload here -->
	</noscript>         
</div> <!--
<br />
<br />
<br />
<div id="file-uploader-demo2">		
	<noscript>			
		<p>Please enable JavaScript to use file uploader.</p>
	</noscript>         
</div>
<%= link_to 'Invite Collaborators', project_collaborators_path(@project) %>
<%= link_to "+ New Task", new_project_task_path(@project) %>
-->
<p id="notice"><%= notice %></p>

<script>
	$("#new").click(function() {
	  window.location = "/projects/" + <%= @project.id %> + "/tasks/new";
	});
	$("#collaborators").click(function() {
	  window.location = "/projects/" + <%= @project.id %> + "/collaborators";
	});

	function createUploader(){            
	    var uploader = new qq.FileUploader({
	        element: document.getElementById('file-uploader-demo1'),
	        action: 'do-nothing.htm',
	        debug: true
	    });           
	}

	function createUploader2(){            
	    var uploader = new qq.FileUploader({
	        element: document.getElementById('file-uploader-demo2'),
	        action: 'do-nothing.htm',
	        debug: true
	    });           
	}
	
	function createAll(){
		createUploader();
//		createUploader2();
	}

    // in your app create uploader as soon as the DOM is ready
    // don't wait for the window to load  
    window.onload = createAll;     
</script>