config/routes.rb
Tasks::Application.routes.draw do

  resources :attachments
  
  get 'projects/dashboard'
  resources :projects do
    resources :tasks do
      get 'complete'
      collection do
        get 'people'
      end
    end
    resources :collaborators
  end

  devise_for :users

  get "home/after_sign_in"
  get "home/index"

  root :to => 'home#index'

end

app/views/layouts/1column.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<script>

	$(function() {  

		$(document).ready(function(){
			$('#instant_input').focus();
		});

		$("#instant_input").keypress(function() { // not work for chinese input
			$('#myModal').modal('show');
			$('#myModal').on('shown', function(){
				$('.new_task_title').val($('#instant_input').val());
				$(".new_task_title").focus();
			});
		});

		$('#myModal').on('hidden', function(){
			$('#instant_input').val('');
			$('#instant_input').focus();
		});

	});

	</script>
</head>

<body>

	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
				<a class="brand" href="#">Tasks</a>
				<ul class="nav">
				  <li class="dropdown" id="menu1">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
				      Project
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
							<% @projects = Project.all %>
							<% @projects.each do |project| %>
				      <li><%= link_to project.name, project_tasks_path(project) %></li>
							<% end %>
				      <li class="divider"></li>
				      <li><%= link_to "+ Create Project", new_project_path %></li>
				    </ul>
				  </li>
					<li class="divider-vertical"></li>
					<li>
						<%= text_field_tag 'instant_input', nil, :class => "span3 mt5", :placeholder => "Create task instantly..." %>
					</li>
					<li>
						<div class="drop-create span2">Drop files to create...</div>
					</li>
				</ul>
				<ul class="nav pull-right">
					<li class="divider-vertical"></li>
				  <li class="dropdown" id="menu2">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu2">
				      <%= current_user.username %>
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
				      <li><%= link_to 'Settings' %></li>
				      <li class="divider"></li>
				      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				    </ul>
				  </li>
				</ul>
				<div class="pull-right">
						<form class="navbar-search">
					  	<input type="text" class="search-query span2" placeholder="Search">
						</form>
				</div>
	    </div>
	  </div>
	</div>

	<div id='page-outer'>
		<div id='page-container'>
			<div class="clearfix">
				<%= render 'shared/project_menu' %>
				<%= yield %>
			</div>
		</div>
	</div>

	<% if !@project.nil? && !@new_task.nil? %>
	<div class="modal fade hide" id="myModal">
		<div id="task-form"><%= render "tasks/form" %></div>
	</div>
	<% end %>
</body>
</html>

app/views/layouts/2column.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<script>

	$(function() {
		
		$(document).ready(function(){
			$('#instant_input').focus();
		});

		$("#instant_input").keypress(function() { // not work for chinese input
			$('#myModal').modal({'backdrop': 'static', 'show': true});
			$('#myModal').on('shown', function(){
				$('#task_title').val($('#instant_input').val());
				$("#task_title").focus();
			});
		});

		$('#myModal').on('hidden', function(){
			$('#instant_input').val('');
			$('#instant_input').focus();
		});

	});

	</script>
</head>

<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
				<a class="brand" href="#">Tasks</a>
				<ul class="nav">
				  <li class="dropdown" id="menu1">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
				      Project
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
							<% @projects = Project.all %>
							<% @projects.each do |project| %>
				      <li><%= link_to project.name, project_tasks_path(project) %></li>
							<% end %>
				      <li class="divider"></li>
				      <li><%= link_to "+ Create Project", new_project_path %></li>
				    </ul>
				  </li>
					<li class="divider-vertical"></li>
					<% if !@project.nil? %>
					<li>
						<%= text_field_tag 'instant_input', nil, :class => "span3 mt5", :placeholder => "Create task instantly..." %>
					</li>
					<li>
						<div class="drop-create span2">Drop files to create...</div>
					</li>
					<% end %>
				</ul>
				<ul class="nav pull-right">
					<li class="divider-vertical"></li>
				  <li class="dropdown" id="menu2">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu2">
				      <%= current_user.username %>
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
				      <li><%= link_to 'Settings' %></li>
				      <li class="divider"></li>
				      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				    </ul>
				  </li>
				</ul>
				<div class="pull-right">
						<form class="navbar-search">
					  	<input type="text" class="search-query span2" placeholder="Search">
						</form>
				</div>
	    </div>
	  </div>
	</div>

	<div id='page-outer'>
		<div id='page-container'>
			<div class="clearfix">
				<%= render 'shared/project_menu' %>
				<div class="list">
					<%= yield %>
				</div>
				<div class="updates">
				</div>
			</div>
		</div>
	</div>

	<% if !@project.nil? && !@new_task.nil? %>
	<div class="modal fade hide" id="myModal">
		<div id="task-form"><%= render "tasks/form" %></div>
	</div>
	<% end %>
</body>
</html>

app/views/layouts/____create-task.html.erb
<%= form_for([@project, @task], :html => {:class => "form-horizontal"}) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="modal-body">
  <fieldset>
    <div class="control-group">
      <label class="control-label short-label" for="title">Content:</label>
      <div class="controls short-content">
        <%= f.text_field :title, :class => 'input-xlarge' %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label short-label" for="detail">More info:</label>
      <div class="controls short-content">
        <%= f.text_area :detail, :class => 'input-xlarge', :rows => 3 %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label short-label" for="detail">Due:</label>
      <div class="controls short-content">
      </div>
    </div>
    <div class="control-group">
      <label class="control-label short-label" for="detail">Assign:</label>
      <div class="controls short-content">
				<%= f.select :assignee_id, @project.collaborators.all.collect {|c| [c.user.username, c.user_id]}, {:selected => current_user.id} %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label short-label" for="detail">Documents:</label>
      <div class="controls short-content">
		<div class="drag-drop-area input-xlarge">Drag and drop files here...</div>
		or <input class="input-file" type="file">
      </div>
    </div>
  </fieldset>
</div>
<div class="modal-footer">
  <a href="#" class="btn" data-dismiss="modal">Cancel</a>
  <%= f.submit :class => 'btn btn-primary' %>
</div>
<% end %>  

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
	
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
				<a class="brand" href="#">Actions.io</a>
				<ul class="nav">
				  <li class="dropdown" id="menu1">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
				      Project
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
							<% @projects = Project.all %>
							<% @projects.each do |project| %>
				      <li><%= link_to project.name, project_tasks_path(project) %></li>
							<% end %>
				      <li class="divider"></li>
				      <li><%= link_to "+ Create Project", new_project_path %></li>
				    </ul>
				  </li>
					<li class="divider-vertical"></li>
					<li>
						<%= text_field_tag 'instant_input', nil, :class => "span3 mt5", :placeholder => "Create task instantly..." %>
					</li>
					<li>
						<div class="drop-create span2">Drop files to create...</div>
					</li>
				</ul>
				<ul class="nav pull-right">
					<li class="divider-vertical"></li>
				  <li class="dropdown" id="menu2">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu2">
				      Profile
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
				      <li><%= link_to 'Settings' %></li>
				      <li class="divider"></li>
				      <li><%= link_to "Sign out" %></li>
				    </ul>
				  </li>
				</ul>
				<div class="pull-right">
						<form class="navbar-search">
					  	<input type="text" class="search-query span2" placeholder="Search">
						</form>
				</div>
	    </div>
	  </div>
	</div>

	<div id='page-outer'>
		<div id='page-container'>
			<%= render 'shared/project_menu' %>
			<div class="dashboard">
				<div class="module">
					<ul class="nav nav-list">
					  <li class="nav-header">
					    Project Admin
					  </li>
					  <li<% if action_name == "edit" %> class="active"<% end %>>
					    <%= link_to "Basic settings", edit_project_path(@project) %></a>
					  </li>
					  <li<% if action_name == "index" %> class="active"<% end %>>
					    <%= link_to "Collaborators", project_collaborators_path(@project) %>
					  </li>
					</ul>
				</div>
			</div>
			<div class="admin-content">
				<div class="content-header">
					<div class="header-inner">
						<h2><%= @function %></h2>
					</div>
				</div>
				<div class="content-inner no-stream-end">
					<%= yield %>
				</div>
			</div>
		</div>
	</div>

	
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
	<%= yield %>
</div>

</body>
</html>

app/views/layouts/people.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<script>

	$(function() {  

		$(document).ready(function(){
			$('#instant_input').focus();
		});

		$("#instant_input").keypress(function() { // not work for chinese input
			$('#myModal').modal('show');
			$('#myModal').on('shown', function(){
				$('#task_title').val($('#instant_input').val());
				$("#task_title").focus();
			});
		});

		$('#myModal').on('hidden', function(){
			$('#instant_input').val('');
			$('#instant_input').focus();
		});

	});

	</script>
</head>

<body>

	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
				<a class="brand" href="#">Tasks</a>
				<ul class="nav">
				  <li class="dropdown" id="menu1">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
				      Project
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
							<% @projects = Project.all %>
							<% @projects.each do |project| %>
				      <li><%= link_to project.name, project_tasks_path(project) %></li>
							<% end %>
				      <li class="divider"></li>
				      <li><%= link_to "+ Create Project", new_project_path %></li>
				    </ul>
				  </li>
					<li class="divider-vertical"></li>
					<li>
						<%= text_field_tag 'instant_input', nil, :class => "span3 mt5", :placeholder => "Create task instantly..." %>
					</li>
					<li>
						<div class="drop-create span2">Drop files to create...</div>
					</li>
				</ul>
				<ul class="nav pull-right">
					<li class="divider-vertical"></li>
				  <li class="dropdown" id="menu2">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu2">
				      <%= current_user.username %>
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
				      <li><%= link_to 'Settings' %></li>
				      <li class="divider"></li>
				      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				    </ul>
				  </li>
				</ul>
				<div class="pull-right">
						<form class="navbar-search">
					  	<input type="text" class="search-query span2" placeholder="Search">
						</form>
				</div>
	    </div>
	  </div>
	</div>

	<div id='page-outer'>
		<div id='page-container'>
			<div class="clearfix">
				<%= render 'shared/project_menu' %>
				<%= yield %>
			</div>
		</div>
	</div>

	<% if !@project.nil? && !@task.nil? %>
	<div class="modal fade hide" id="myModal">
		<div id="task-form"><%= render "tasks/form" %></div>
	</div>
	<% end %>
</body>
</html>

app/views/layouts/project_admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
	
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
				<a class="brand" href="#">Actions.io</a>
				<ul class="nav">
				  <li class="dropdown" id="menu1">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
				      Project
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
							<% @projects = Project.all %>
							<% @projects.each do |project| %>
				      <li><%= link_to project.name, project_tasks_path(project) %></li>
							<% end %>
				      <li class="divider"></li>
				      <li><%= link_to "+ Create Project", new_project_path %></li>
				    </ul>
				  </li>
					<li class="divider-vertical"></li>
					<li>
						<%= text_field_tag 'instant_input', nil, :class => "span3 mt5", :placeholder => "Create task instantly..." %>
					</li>
					<li>
						<div class="drop-create span2">Drop files to create...</div>
					</li>
				</ul>
				<ul class="nav pull-right">
					<li class="divider-vertical"></li>
				  <li class="dropdown" id="menu2">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu2">
				      Profile
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
				      <li><%= link_to 'Settings' %></li>
				      <li class="divider"></li>
				      <li><%= link_to "Sign out" %></li>
				    </ul>
				  </li>
				</ul>
				<div class="pull-right">
						<form class="navbar-search">
					  	<input type="text" class="search-query span2" placeholder="Search">
						</form>
				</div>
	    </div>
	  </div>
	</div>

	<div id='page-outer'>
		<div id='page-container'>
			<div>
				<div class="page-top">
					<% if !@project.id.nil? %>
					<h2><%= @project.name %></h2>
					<div class="btn-group pull-right">
					  <button class="btn <% if action_name == 'index'%>active<%end%>"><%= link_to "Tasks", project_tasks_path(@project) %></button>
					  <button class="btn"><a data-toggle="modal" href="#myModal" >People</a></button>
					  <button class="btn <% if action_name == 'show'%>active<%end%>"><%= link_to "Admin", edit_project_path(@project) %></button>
					</div>
					<% end %>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="container-fluid">
			  <div class="row-fluid">
					<div class="panel span2" style="padding:8px 0;">
						<div class="panel-inner">
							<ul class="nav nav-list">
							  <li class="nav-header">
							    List header
							  </li>
							  <li class="active">
							    <a href="#">Home</a>
							  </li>
							  <li>
							    <a href="#">Library</a>
							  </li>
							  ...
							</ul>
						</div>
			      <!--Sidebar content-->
			    </div>
			    <div class="span10">
						<%= yield %>
			      <!--Body content-->
			    </div>
			  </div>
			</div>
		</div>
	</div>

	
</body>

</html>

app/views/layouts/twitter.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<script>

	$(function() {
		
		$(document).ready(function(){
			$('#instant_input').focus();
		});

		$("#instant_input").keypress(function() { // not work for chinese input
			$('#myModal').modal({'backdrop': 'static', 'show': true});
			$('#myModal').on('shown', function(){
				$('#task_title').val($('#instant_input').val());
				$("#task_title").focus();
			});
		});

		$('#myModal').on('hidden', function(){
			$('#instant_input').val('');
			$('#instant_input').focus();
		});

	});

	</script>
</head>

<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
				<a class="brand" href="#">Tasks</a>
				<ul class="nav">
				  <li class="dropdown" id="menu1">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
				      Project
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
							<% @projects = Project.all %>
							<% @projects.each do |project| %>
				      <li><%= link_to project.name, project_tasks_path(project) %></li>
							<% end %>
				      <li class="divider"></li>
				      <li><%= link_to "+ Create Project", new_project_path %></li>
				    </ul>
				  </li>
					<li class="divider-vertical"></li>
					<% if !@project.nil? %>
					<li>
						<%= text_field_tag 'instant_input', nil, :class => "span3 mt5", :placeholder => "Create task instantly..." %>
					</li>
					<li>
						<div class="drop-create span2">Drop files to create...</div>
					</li>
					<% end %>
				</ul>
				<ul class="nav pull-right">
					<li class="divider-vertical"></li>
				  <li class="dropdown" id="menu2">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu2">
				      <%= current_user.username %>
				      <b class="caret"></b>
				    </a>
				    <ul class="dropdown-menu">
				      <li><%= link_to 'Settings' %></li>
				      <li class="divider"></li>
				      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				    </ul>
				  </li>
				</ul>
				<div class="pull-right">
						<form class="navbar-search">
					  	<input type="text" class="search-query span2" placeholder="Search">
						</form>
				</div>
	    </div>
	  </div>
	</div>

	<div id='page-outer'>
		<div id='page-container'>
			<div class="clearfix">
				<%= render 'shared/project_menu' %>
				<div class="list">
					<%= yield %>
				</div>
				<div class="updates">
				</div>
			</div>
		</div>
	</div>

	<% if !@project.nil? && !@task.nil? %>
	<div class="modal fade hide" id="myModal">
		<div id="task-form"><%= render "tasks/form" %></div>
	</div>
	<% end %>
</body>
</html>

app/views/layouts/white.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
	<%= render 'shared/topbar' %>
	<div id='page-outer'>
		<div id='page-container'>
				<%= yield %>
		</div>
	</div>

</body>
</html>